# Elliot C
# 9/20/24

from time import sleep

print()
print()
print()
fname = input("What is your first name?")
fgame = input("Any favorite video game?")
sentence = "Hello, " + fname + ", player of the hit video game " + fgame + "."
print(sentence)
print()
sleep(1)
print()
sleep(1)
print()
print("I used concatenation for this.")
print("Concatenation sucks.")
sleep(2)
print("It's anoying, f strings are better.")
sleep(3)
print("It's slow, because it takes up to much memory.")
sleep(3)
print("It's anoying to code it this way.")
sleep(3)
print("It all around is a bad option.")
print()
sleep(1)
print()
sleep(1)
print()
sleep(5)
bkb = float(75946.32)
print("Anyways, that will be $" + str(bkb) + " at the first window.")
print("Thank you for comming to Burger King today.")